name 'mesos'
maintainer 'John Manero'
maintainer_email 'john.manero@gmail.com'
license 'All rights reserved'
description 'Installs/Configures mesos'
long_description 'Installs/Configures mesos'
version '0.1.0'

depends 'apt'
depends 'build-essential'
